provider:
  name: openfaas
  gateway: http://127.0.0.1:8080

functions:
  hello-python:
    lang: python3-http
    handler: ./
    image: hello-python
    environment:
      write_debug: true
      combine_output: false
